date: "2025.11.24"
work_dir: "D:/Lab"

raw_data_dir: "D:/Lab/raw/2025.11.24"
tdms_reader_time_output_dir: "D:/Lab/process/2025.11.24/time"
tdms_reader_frequency_output_dir: "D:/Lab/process/2025.11.24/frequency"
tdms_reader_frequency_average_output_dir: "D:/Lab/process/2025.11.24/frequency_ave"
time_series_results_dir: "D:/Lab/results/2025.11.24/time"
frequency_results_dir: "D:/Lab/results/2025.11.24/frequency"
database_path: "D:/Lab/database/lab_data.db"