date: "26.3.9"
work_dir: "D:/Lab"

raw_data_dir: "D:/Lab/raw/26.3.9"
tdms_reader_time_output_dir: "D:/Lab/process/26.3.9/time"
tdms_reader_frequency_output_dir: "D:/Lab/process/26.3.9/frequency"
tdms_reader_frequency_average_output_dir: "D:/Lab/process/26.3.9/frequency_ave"
time_series_results_dir: "D:/Lab/results/26.3.9/time"
frequency_results_dir: "D:/Lab/results/26.3.9/frequency"
database_path: "D:/Lab/database/lab_data.db"
