date: "26.5.12"
work_dir: "D:/Lab"

raw_data_dir: "D:/Lab/raw/26.5.12"
tdms_reader_time_output_dir: "D:/Lab/process/26.5.12/time"
tdms_reader_frequency_output_dir: "D:/Lab/process/26.5.12/frequency"
tdms_reader_frequency_average_output_dir: "D:/Lab/process/26.5.12/frequency_ave"
time_series_results_dir: "D:/Lab/results/26.5.12/time"
frequency_results_dir: "D:/Lab/results/26.5.12/frequency"
database_path: "D:/Lab/database/lab_data.db"
